promptToReturnFromSubprocess: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  diffAddedColor:
    - orange # Change from green to blue for added lines
  diffRemovedColor:
    - teal # Change from red to magenta for removed lines theme:
  lightTheme: false
  activeBorderColor:
    - "#98BB6C" # Kanagawa springGreen
    - bold
  inactiveBorderColor:
    - "#363646" # Kanagawa sumiInk2
  optionsTextColor:
    - "#DCA561" # Kanagawa autumnYellow
  selectedLineBgColor:
    - "#2A2A37" # Kanagawa sumiInk4
  selectedRangeBgColor:
    - "#2A2A37" # Kanagawa sumiInk4
  cherryPickedCommitBgColor:
    - "#2A2A37" # Kanagawa sumiInk4
  cherryPickedCommitFgColor:
    - "#957FB8" # Kanagawa sakuraPink (lavender)
  unstagedChangesColor:
    - "#C34043" # Kanagawa autumnRed
  defaultFgColor:
    - "#DCD7BA" # Kanagawa fujiWhite
  searchingActiveBorderColor:
    - "#FF9E3B" # Kanagawa surimiOrange
  commandBarBgColor:
    - "#1F1F28" # Kanagawa sumiInk1
  commandBarFgColor:
    - "#DCD7BA" # Kanagawa fujiWhite
  fileStagingTitleColor:
    - "#7FB4CA" # Kanagawa waveAqua1
  mainPanelBgColor:
    - "#16161D" # Kanagawa sumiInk0
  menuBgColor:
    - "#1F1F28" # Kanagawa sumiInk1
  menuFgColor:
    - "#DCD7BA" # Kanagawa fujiWhite
  mergedCommitBgColor:
    - "#2B3328" # Darker version of springGreen
  mergedCommitFgColor:
    - "#98BB6C" # Kanagawa springGreen
  stagedChangesColor:
    - "#76946A" # Kanagawa waveGreen2
